project:
  type: book
  output-dir: _book

book:
  title: "Subhojit's Academic Journey"
  author: "Subhojit Maji"
  date: "last-modified"
  favicon: "images/Dk Logo.png"
  
  sidebar:
    title: |
      <span class="handwriting">Subhojit Maji </span>
      <span class="icon-line"></span>
    style: floating
    background: "rgba(250, 245, 255, 0.9)"
    collapse-level: 1
    tools:
      - icon: house-heart
        href: index.html
      - icon: github
        href: https://github.com/SubhojitMaji
      - icon: journal-code
        href: content/UDGRP 2024.qmd

  chapters:
    - index.qmd
    - content/intro.qmd
    - content/ALL-ZEBRA.qmd
    - content/PUZZLES.qmd
    - part: "Creative Pursuits"
      chapters:
        - content/Latex.qmd
    - part: "Projects/Additional Work"
      chapters:
        - content/UDGRP 2024.qmd
    - content/acheivements.qmd
    - content/summary.qmd

format:
  html:
    theme: yeti
    css: styles/one.css
    include-in-header:
      - text: |
          <script src="scripts/scroll-animations.js"></script>
    toc: false
    number-sections: false
    toc-location: left
    smooth-scroll: true
    grid:
      sidebar-width: 300px
      body-width: 1000px
    code-tools: true
    code-copy: true