---
format: html
target: _blank
from: markdown+emoji
editor: visual
---

:::{.content-container}

# Academic Portfolio {.section-title}

:::{.highlight-card .primary}
## Semester I Coursework

### Real Analysis I
- Instructor: [**BV Rajarama Bhatt**](https://www.isibang.ac.in/~bhat/)
- [Course Notes](https://drive.google.com/file/d/15aQW5bT4oBRqTgWve05l_CL1jxj97ieQ/view?usp=sharing)

### Fundamentals of Computer Programming
- Instructor: [**Jishnu Gupta Biswas**](https://isi.irins.org/profile/13204)
- [Course Page](https://www.isibang.ac.in/~adean/infsys/database/Bmath/FCP.html)
- [C Programming Reference](https://drive.google.com/file/d/1JgIz5I723BBlrkGD4n0qE4n5U89LD3XY/view?usp=sharing)

### Probability I
- Instructor: [**Mathew Joseph**](https://sites.google.com/view/mjoseph/home)
- [Assignment Collection](https://www.dropbox.com/scl/fo/82fhg93xrqu7uu2c9zee7/AJAjDMG9mTI_YDe6AzGnzjw?rlkey=n5rox1f2oxt2jyz5v8lkga463&st=482hedgr&dl=0)

### Elementary Number Theory
- Instructor: [**Ramdin Mawia**](https://sites.google.com/view/ramdinmawia/home)
- [Assignment Collection](https://drive.google.com/file/d/1a-w8kH7kZud-1WypK9IrwDW7UoYUFmZf/view?usp=sharing)

### Linear Algebra I
- Instructor: [**Anita Naolekar**](https://www.isibang.ac.in/~statmath/homepage.html)
- [Course Details](https://www.isibang.ac.in/~adean/infsys/database/Bmath/LAlg1.html)
:::



:::{.highlight-card .primary}
## Semester II Coursework

### Real Analysis II
- Instructor: [**Jaydeb Sarkar**](https://www.isibang.ac.in/~jay/)
- [Course Page](https://www.isibang.ac.in/~adean/infsys/database/Bmath/RA2.html)

### Numerical Computing
- Instructor: [**Jishnu Gupta Biswas**](https://isi.irins.org/profile/13204)
- [Course Page](https://www.isibang.ac.in/~adean/infsys/database/Bmath/NC.html)
- [Numerical Computing Reference](https://www.amazon.in/Numerical-Mathematics-Computing-Ward-Cheney/dp/813151952X)

### Probability II
- Instructor: [**Mathew Joseph**](https://sites.google.com/view/mjoseph/home)
- [Assignment Collection](https://drive.google.com/drive/folders/1-s3dbt0HidTG4zpwj6ixsZmCyAFiOAnG?q=sharedwith:public%20parent:1-s3dbt0HidTG4zpwj6ixsZmCyAFiOAnG)

### Statistics I
- Instructor: [**Rituparna Sen**](https://www.isibang.ac.in/~rsen/)
- [Course Page](https://www.isibang.ac.in/~adean/infsys/database/Bmath/SCD.html)

### Linear Algebra II
- Instructor: [**Anita Naolekar**](https://www.isibang.ac.in/~statmath/homepage.html)
- [Course Details](https://www.isibang.ac.in/~adean/infsys/database/Bmath/LAlg2.html)
:::

:::{.highlight-card .success}
## Beyond Academics
- **Cultural Committee Representative** : Curated diverse cultural experiences, fostering a global atmosphere on campus.
- **Design Team Manager for [LIMIT](https://www.limitisi.in)** : Honed creative vision and communication skills, led a design team.
- **Active participation in campus life and student activities** : Connected with peers and forged lasting friendships.
:::

:::